// -*- mode: java; c-basic-offset: 2; -*-
// Copyright 2025 MIT, All rights reserved
// Released under the Apache License, Version 2.0
// http://www.apache.org/licenses/LICENSE-2.0

package com.google.appinventor.components.scripts;

import java.io.IOException;
import java.io.PrintWriter;
import java.io.Writer;
import java.util.Map;

public class WebComponentFactoryGenerator extends ComponentProcessor {
  private static final String WEBEMU_PACKAGE = "edu.mit.appinventor.webemu";

  @Override
  protected void outputResults() throws IOException {
    try (Writer writer = createOutputFileObject(WEBEMU_PACKAGE, "ComponentFactory.java").openWriter()) {
      PrintWriter pw = new PrintWriter(writer);
      printHeader(pw);
      pw.println("import java.util.HashMap;");
      pw.println("import java.util.Map;");
      pw.println("import jsinterop.annotations.JsType;");
      pw.println();
      pw.println("@JsType(namespace = \"appinventor\")");
      pw.println("public class ComponentFactory {");
      pw.println("  @FunctionalInterface");
      pw.println("  interface ComponentConstructor<T> {");
      pw.println("    T create(ComponentContainer parent);");
      pw.println("  }");
      pw.println("  private static final Map<String, ComponentConstructor<? extends Component>> LOOKUP = new HashMap<>();");
      pw.println();
      pw.println("  static {");
      for (Map.Entry<String, ComponentInfo> component : components.entrySet()) {
        ComponentInfo info = component.getValue();
        if (!info.webemulation) {
          continue;
        }
        String type = component.getKey();
        if (type.startsWith("com.google.appinventor.components.runtime.")) {
          type = type.substring("com.google.appinventor.components.runtime.".length());
        }
        pw.println("    LOOKUP.put(\"" + type + "\", " + type + "::new);");
        outputClassDefinition(info);
      }
      pw.println("  }");
      pw.println();
      pw.println("  @SuppressWarnings(\"unusable-by-js\")");
      pw.println("  public static Component create(ComponentContainer parent, String type) {");
      pw.println("    if (type.startsWith(\"com.google.appinventor.components.runtime.\")) {");
      pw.println("      type = type.substring(\"com.google.appinventor.components.runtime.\".length());");
      pw.println("    }");
      pw.println("    ComponentConstructor<? extends Component> constructor = LOOKUP.get(type);");
      pw.println("    if (constructor == null) {");
      pw.println("      throw new IllegalArgumentException(\"Unknown component type: \" + type);");
      pw.println("    }");
      pw.println("    return constructor.create(parent);");
      pw.println("  }");
      pw.println("}");
      pw.flush();
    }
  }

  private void printHeader(PrintWriter pw) {
    pw.println("// -*- mode: java; c-basic-offset: 2; -*-");
    pw.println("// Copyright 2025 MIT, All rights reserved");
    pw.println("// Released under the Apache License, Version 2.0");
    pw.println("// https://www.apache.org/licenses/LICENSE-2.0");
    pw.println("// DO NOT EDIT THIS FILE - IT IS AUTOMATICALLY GENERATED BY WebComponentFactoryGenerator");
    pw.println();
    pw.println("package edu.mit.appinventor.webemu;");
    pw.println();
    pw.println("import com.google.appinventor.components.runtime.Component;");
    pw.println("import com.google.appinventor.components.runtime.ComponentContainer;");
  }

  private void outputClassDefinition(ComponentInfo component) throws IOException {
    String type = component.type;
    String name = component.name;
    try (Writer writer = createOutputFileObject("edu.mit.appinventor.webemu",
        name + ".java").openWriter()) {
      PrintWriter pw = new PrintWriter(writer);
      printHeader(pw);
      pw.println("import jsinterop.annotations.JsMethod;");
      pw.println("import jsinterop.annotations.JsProperty;");
      pw.println();
      pw.println("public class " + name + " extends " + type + " {");
      pw.println("  public " + name + "(ComponentContainer container) {");
      pw.println("    super(container);");
      pw.println("  }\n");
      for (Map.Entry<String, Method> entry : component.methods.entrySet()) {
        String methodName = entry.getKey();
        Method method = entry.getValue();
        pw.println("  @JsMethod(name = \"" + methodName + "\")");
        pw.print("  public ");
        if (method.isStatic()) {
          pw.print("static ");
        }
        if (method.getReturnType() == null) {
          pw.print("void ");
        } else {
          pw.print(method.getReturnType() + " ");
        }
        pw.print(methodName + "(");
        boolean first = true;
        for (Parameter param : method.parameters) {
          if (!first) {
            pw.print(", ");
          }
          if (param.type.toString().equals("long")) {
            // JS doesn't have 64-bit integers, so we use int instead
            pw.print("int " + param.name);
          } else {
            pw.print(param.type + " " + param.name);
          }
          first = false;
        }
        pw.println(") {");
        pw.print("    ");
        if (method.getReturnType() != null) {
          pw.print("return ");
        }
        if (method.isStatic()) {
          pw.print(component.type + "." + methodName + "(");
        } else {
          pw.print("super." + methodName + "(");
        }
        first = true;
        for (Parameter param : method.parameters) {
          if (!first) {
            pw.print(", ");
          }
          pw.print(param.name);
          first = false;
        }
        pw.println(");");
        pw.println("  }\n");
      }
      for (Map.Entry<String, Property> entry : component.properties.entrySet()) {
        String propertyName = entry.getKey();
        Property property = entry.getValue();
        if (property.isReadable()) {
          pw.println("  @JsProperty(name = \"" + propertyName + "\")");
          pw.print("  public ");
          pw.print(property.getType() + " ");
          pw.println(propertyName + "() {");
          pw.println("    return super." + propertyName + "();");
          pw.println("  }\n");
        }
        if (property.isWritable()) {
          pw.println("  @JsProperty(name = \"" + propertyName + "\")");
          pw.print("  public void ");
          pw.println(propertyName + "(" + property.getType() + " value) {");
          pw.println("    super." + propertyName + "(value);");
          pw.println("  }\n");
        }
      }
      pw.println("}");
    }
  }
}
